sudo:
  false

language:
  python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5

before_install:
  - openssl aes-256-cbc -K $encrypted_89004861c545_key -iv $encrypted_89004861c545_iv -in .credentials.json.enc -out .credentials.json -d

env:
  global:
    - TOXENV="py${PYTHON_VERSION//./}"
  matrix:
    - SOURCE=git
    - SOURCE=pypi

install:
  - make install-${SOURCE}

script:
  - make test

notifications:
  slack:
    secure: VL0ASfIx+Bp9+78+iGgyGtcFsvMTCFZZWN0FlHGm8SmPyNwu54hOOS7TnINgJnF36531csvz+BRlC3w15jvhuwdJm0NL4VsulaPJmaa/8cdtYonfUisg6op9XXuUHUwKZA9bFqOlLT8nXf5pxJIm4BuflBNYJZzU9OEB0EvDOFD2OIKAplIz0ny/Dnb9BilELD/SBbRLGw83Lb1XFOsVnhDCM4Ng0uHLHcANMr9OnAtHSM/dbvwGYTWbzM9cI7sH9SbPJ3bJgI/SFG9kdallw5odnWiOai6Xk7ZjOirzuLq8XCS6eoDy5L3JYIKfxgdqpRwz54w/uFGde47JFfo10yCbOmb1XF7V5F+RibYWfMoadadds97t/h1I5EzeOdgdc0urZ5l0QNE7NqvWUds9tj8VR+aChdQwCkTIRiQimfrwT54OAk+clGf1GTZXC6w/WjNl7Pm+7dCM+A2aCmHRQRS7SZgIEWKMDDQXFqMH+MXxtLJ9p/2tWoTvp9WQK9ppZHf0Zc+b0wkKEwXlDYeX97gdexyBf6v4cs69SM1B8kC0a4bskhNcKE41ir0qhpUIUcSPS8FKDHadFiHK5QZGP2BIkCD2qMHFroSTwRCsfx6EJyIiBDekHrZJZcOHmb/fYOrzgQ3xoubh1+waZ0m8fzicvqP/BQNGCGbi7i0voVo=
    on_success: always
    on_failure: always
    on_pull_requests: false
